TiendaComida/Models/Comida.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaComida.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comida
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comida()
        {
            this.Categoria = new HashSet<Categoria>();
            this.ComidaImagen = new HashSet<ComidaImagen>();
            this.PedidoDetalle = new HashSet<PedidoDetalle>();
        }
    
        public int ComidaId { get; set; }
        public string Denominacion { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public int Existencias { get; set; }
        public string ValorNutricional { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categoria> Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComidaImagen> ComidaImagen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoDetalle> PedidoDetalle { get; set; }
    }
}

TiendaComida/Areas/Admin/Controllers/ComidaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TiendaComida.Models;

namespace TiendaComida.Areas.Admin.Controllers
{
    public class ComidaController : Controller
    {
        private ComidaDBEntities3 db = new ComidaDBEntities3();

        // GET: Admin/Comida
        public ActionResult Index()
        {
            return View(db.Comida.ToList());
        }

        // GET: Admin/Comida/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comida comida = db.Comida.Find(id);
            if (comida == null)
            {
                return HttpNotFound();
            }
            return View(comida);
        }

        // GET: Admin/Comida/Create
        public ActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ComidaId,Denominacion,Descripcion,Precio,Existencias,ValorNutricional,Activo")] Comida comida)
        {
            if (ModelState.IsValid)
            {
                db.Comida.Add(comida);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(comida);
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comida comida = db.Comida.Find(id);
            if (comida == null)
            {
                return HttpNotFound();
            }
            return View(comida);
        }

      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ComidaId,Denominacion,Descripcion,Precio,Existencias,ValorNutricional,Activo")] Comida comida)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comida).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(comida);
        }

        // GET: Admin/Comida/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comida comida = db.Comida.Find(id);
            if (comida == null)
            {
                return HttpNotFound();
            }
            return View(comida);
        }

        // POST: Admin/Comida/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comida comida = db.Comida.Find(id);
            db.Comida.Remove(comida);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }








        public JsonResult Adjuntar(int ComidaId, HttpPostedFileBase documento)
        {
            var respuesta = new ResponseModel
            {
                respuesta = true,
                error = ""
            };

            if (documento != null)
            {
                string adjunto = DateTime.Now.ToString("yyyyMMddHHmmss") + Path.GetExtension(documento.FileName);
                documento.SaveAs(Server.MapPath("~/ImgProductos/" + adjunto));

                db.ComidaImagen.Add(new ComidaImagen { ComidaId = ComidaId, Imagen = adjunto, Titulo = "Ejemplo", Descripcion = "Ejemplo" });
                db.SaveChanges();

            }
            else
            {
                respuesta.respuesta = false;
                respuesta.error = "Debe adjuntar un documento";
            }

            return Json(respuesta);
        }

        public PartialViewResult Adjuntos(int ComidaId)
        {
            return PartialView(db.ComidaImagen.Where(x => x.ComidaId == ComidaId).ToList());
        }



        public JsonResult EliminarImagen(int ComidaImagenId)
        {
            var rpt = new ResponseModel()
            {
                respuesta = true,
                error = ""
            };
            var img = db.ComidaImagen.Find(ComidaImagenId);

            if (System.IO.File.Exists(Server.MapPath("~/ImgProductos/" + img.Imagen)))
                System.IO.File.Delete(Server.MapPath("~/ImgProductos/" + img.Imagen));

            db.ComidaImagen.Remove(img);
            db.SaveChanges();

            return Json(rpt);
        }



    }
}

TiendaComida/Controllers/ComidasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TiendaComida.Models;

namespace TiendaComida.Controllers
{
    public class ComidasController : Controller
    {
        // GET: Comida
        public ActionResult Buscar(string id = "")
        {
            //el resultado de la busqueda de comidas
            ViewBag.Clave = id;
            var comidas = new List<Comida>();
            using (var bd = new ComidaDBEntities3()) {
                comidas = bd.Comida.Include("ComidaImagen").Where(x => x.Denominacion.Contains(id)).ToList();

            }

                return View(comidas);
        }

        public ActionResult MiProceso(string par1, string par2)
        {
            // el resultado de la busqueda de productos
            ViewBag.par1 = par1;
            ViewBag.par2 = par2;
            return View();
        }
    }
}

TiendaComida/Areas/Admin/Views/Comida/Adjuntos.cshtml
@model List<TiendaComida.Models.ComidaImagen>
<div class="row">
    @foreach (var i in Model)
    {
        <div class="col-xs-6 col-md-3">
            <a href="~/ImgProductos/@i.Imagen" class="thumbnail" target="_blank">
                <img src="~/ImgProductos/@i.Imagen" alt="ejemplo" style="width:100px;height:100px">
            </a>
            <p class="text-center"><a href="#" class="btn btn-danger" role="button" onclick="EliminarImagen(@i.ComidaImagenId)">Eliminar</a></p>
        </div>
    }
</div>

TiendaComida/Areas/Admin/Views/Comida/Create.cshtml
@model TiendaComida.Models.Comida

@{
    ViewBag.Title = "Create";
}

<h2>Crear</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Comida</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Denominacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Denominacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Denominacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Existencias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Existencias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Existencias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ValorNutricional, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ValorNutricional, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ValorNutricional, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Activo)
                    @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TiendaComida/Areas/Admin/Views/Comida/Delete.cshtml
@model TiendaComida.Models.Comida

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Comida</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Denominacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Denominacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Existencias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Existencias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorNutricional)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorNutricional)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TiendaComida/Areas/Admin/Views/Comida/Details.cshtml
@model TiendaComida.Models.Comida

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Comida</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Denominacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Denominacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Existencias)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Existencias)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ValorNutricional)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ValorNutricional)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ComidaId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TiendaComida/Areas/Admin/Views/Comida/Edit.cshtml
@model TiendaComida.Models.Comida

@{
    ViewBag.Title = "Edit";
}

<h2>Editar Comida</h2>



<div class="row">

    <div class="col-md-6">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Comida</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ComidaId)

                <div class="form-group">
                    @Html.LabelFor(model => model.Denominacion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Denominacion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Denominacion, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Existencias, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Existencias, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Existencias, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ValorNutricional, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ValorNutricional, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ValorNutricional, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Activo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Activo)
                            @Html.ValidationMessageFor(model => model.Activo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
        </div>


        <div class="col-md-6">

            @if (Model.ComidaId > 0)
            {
                using (Html.BeginForm("Adjuntar", "Comida", FormMethod.Post, new { id = "frm-adjuntar" }))
                {
                    <input type="hidden" name="ComidaId" value="@Model.ComidaId" />
                    <div class="row">
                        <div class="col-xs-10">
                            <div class="form-group">
                                <input type="file" name="documento" accept="image/x-png, image/gif, image/jpeg" @*accept="image/*"*@ />
                            </div>
                        </div>
                        <div class="col-xs-2">
                            <button type="submit" class="btn btn-primary btn-block">Adjuntar</button>
                        </div>
                    </div>
                }
                <div id="adjuntos-cargados"></div>
            }
        </div>


    </div>




    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>
@section scripts{

    <script>
    $(document).ready(function () {
    @if (Model.ComidaId > 0)
    {
        <text>
            CargarAdjuntos();
        </text>
    }

    $("#frm-adjuntar").submit(function () {
    var form = $(this);

    form.ajaxSubmit({
    dataType: 'JSON',
    type: 'POST',
    url: form.attr('action'),
    success: function (r) {
    if (r.respuesta) {
    CargarAdjuntos();
    }
    else { alert(r.error); }
    },
    error: function (jqXHR, textStatus, errorThrown) {
    alert(errorThrown);
    }
    });
    return false;
    })
    });

    function CargarAdjuntos() {
    $("#adjuntos-cargados").load("@Url.Content("~/Admin/Comida/adjuntos?ComidaId=" + Model.ComidaId)");
    }




        function EliminarImagen(ImagenId) {
            $.ajax({
                data: { ComidaImagenId: ImagenId },
                url: '@Url.Action("EliminarImagen","Comida")',
                type: 'post',
                success: function (r) {
                    if (r.respuesta) {
                        CargarAdjuntos();
                    }
                    else
                        alert(r.error);
                },
                error: function (jqXHR, textStatus, errorThrown) { alert(errorThrown); }
            });
        }


    </script>
}

TiendaComida/Areas/Admin/Views/Comida/Index.cshtml
@model IEnumerable<TiendaComida.Models.Comida>

@{
    ViewBag.Title = "Administracion";
}

<h2>Administracion de Comidas</h2>

<p>
    @Html.ActionLink("Crear Producto", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Denominacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Existencias)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ValorNutricional)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Activo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Denominacion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Precio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Existencias)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ValorNutricional)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Activo)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.ComidaId }) |
            @Html.ActionLink("Detalle", "Details", new { id=item.ComidaId }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.ComidaId })
        </td>
    </tr>
}

</table>